# Generated by Django 6.0.2 on 2026-02-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('description', models.TextField()),
                ('semester_suggested', models.IntegerField(help_text='Semestre sugerido del plan de estudios (1-10)')),
                ('language', models.CharField(choices=[('ES', 'Español'), ('EN', 'English'), ('BOTH', 'Bilingüe')], default='ES', max_length=4)),
                ('corequisites', models.ManyToManyField(blank=True, related_name='corequisite_with', to='roadmap.course')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='roadmap.course')),
                ('specializations', models.ManyToManyField(blank=True, related_name='courses', to='roadmap.specialization')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['semester_suggested', 'code'],
            },
        ),
    ]
