# Generated by Django 6.0.2 on 2026-03-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('track_type', models.CharField(choices=[('PROFESSIONAL', 'Profesionalizante'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('credits_required', models.IntegerField(default=0, help_text='Créditos necesarios para completar la trayectoria')),
                ('icon', models.CharField(blank=True, help_text='Clase de Font Awesome (ej: fa-code)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Trayectoria',
                'verbose_name_plural': 'Trayectorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código del curso (puede ser nulo para cursos paraguas)', max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('description', models.TextField()),
                ('semester_suggested', models.IntegerField(help_text='Semestre sugerido del plan de estudios (1-10)')),
                ('language', models.CharField(blank=True, choices=[('ES', 'Español'), ('EN', 'English'), ('BOTH', 'Bilingüe')], default='ES', max_length=4, null=True)),
                ('category', models.CharField(choices=[('BASIC_SCIENCE', 'Ciencias Básicas'), ('BASIC_ENGINEERING', 'Básicas en Ingeniería'), ('NFI', 'NFI'), ('DISCIPLINARY', 'Disciplinar'), ('PROFESSIONAL_TRACK', 'Trayectoria Profesionalizante'), ('FLEXIBLE_TRACK', 'Trayectoria Flexible'), ('PRACTICE', 'Práctica'), ('EMPHASIS', 'Énfasis'), ('SPECIALIZATION', 'Especialización')], default='DISCIPLINARY', help_text='Categoría del curso según el plan de estudios', max_length=30)),
                ('is_umbrella', models.BooleanField(default=False, help_text="Si es un curso paraguas (ej: 'Electiva Matemática I' que tiene múltiples opciones)")),
                ('corequisites', models.ManyToManyField(blank=True, to='roadmap.course')),
                ('parent_course', models.ForeignKey(blank=True, help_text='Si es una opción, aquí va el curso paraguas padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_options', to='roadmap.course')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='roadmap.course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['semester_suggested', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmphasisLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('credits_required', models.IntegerField(default=0, help_text='Créditos necesarios para completar la línea')),
                ('icon', models.CharField(blank=True, help_text='Clase de Font Awesome (ej: fa-star)', max_length=50, null=True)),
                ('specialization', models.ForeignKey(blank=True, help_text='Especialización a la que conduce esta línea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emphasis_lines', to='roadmap.specialization')),
            ],
            options={
                'verbose_name': 'Línea de Énfasis',
                'verbose_name_plural': 'Líneas de Énfasis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_in_specialization', models.IntegerField(help_text='Semestre dentro de la especialización (1-4)')),
                ('is_elective', models.BooleanField(default=True, help_text='True = electivo, False = obligatorio fijo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.course')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.specialization')),
            ],
            options={
                'verbose_name': 'Curso de Especialización',
                'verbose_name_plural': 'Cursos de Especialización',
                'unique_together': {('course', 'specialization')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='courses', through='roadmap.CourseSpecialization', to='roadmap.specialization'),
        ),
        migrations.CreateModel(
            name='EmphasisLineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_in_line', models.IntegerField(help_text='Semestre dentro de la línea (1-2)')),
                ('is_elective', models.BooleanField(default=True, help_text='True = electivo, False = obligatorio fijo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lines', to='roadmap.course')),
                ('emphasis_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_courses', to='roadmap.emphasisline')),
            ],
            options={
                'verbose_name': 'Curso de Línea',
                'verbose_name_plural': 'Cursos de Líneas',
                'ordering': ['semester_in_line'],
                'unique_together': {('emphasis_line', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TrackCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_in_track', models.IntegerField(help_text='Semestre dentro de la trayectoria (1-4)')),
                ('is_elective', models.BooleanField(default=True, help_text='True = electivo, False = obligatorio fijo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tracks', to='roadmap.course')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_courses', to='roadmap.track')),
            ],
            options={
                'verbose_name': 'Curso de Trayectoria',
                'verbose_name_plural': 'Cursos de Trayectorias',
                'ordering': ['semester_in_track'],
                'unique_together': {('track', 'course')},
            },
        ),
    ]
