# Generated by Django 6.0.2 on 2026-03-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emphasisline',
            options={'ordering': ['name'], 'verbose_name': 'Emphasis Line', 'verbose_name_plural': 'Emphasis Lines'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['name'], 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.RemoveField(
            model_name='emphasisline',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='track',
            name='icon',
        ),
    ]
