# Generated by Django 6.0.2 on 2026-02-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='color',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='icon',
        ),
    ]
