# Generated by Django 6.0.2 on 2026-03-20 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_alter_emphasisline_options_alter_track_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='parent_course',
        ),
        migrations.CreateModel(
            name='UmbrellaCourseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_for_umbrellas', to='roadmap.course')),
                ('umbrella_course', models.ForeignKey(limit_choices_to={'is_umbrella': True}, on_delete=django.db.models.deletion.CASCADE, related_name='umbrella_options', to='roadmap.course')),
            ],
            options={
                'verbose_name': 'Opción de Curso Paraguas',
                'verbose_name_plural': 'Opciones de Cursos Paraguas',
                'unique_together': {('umbrella_course', 'option_course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='available_options',
            field=models.ManyToManyField(blank=True, related_name='available_for_umbrellas', through='roadmap.UmbrellaCourseOption', to='roadmap.course'),
        ),
    ]
