# Generated by Django 6.0.2 on 2026-03-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_remove_course_parent_course_umbrellacourseoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umbrellacourseoption',
            options={'verbose_name': 'Umbrella Course Option', 'verbose_name_plural': 'Umbrella Courses Options'},
        ),
    ]
