# Generated by Django 6.0.2 on 2026-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_roadmapstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo en pesos colombianos', max_digits=12, verbose_name='Costo (COP)'),
        ),
    ]
