# Generated by Django 6.0.2 on 2026-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_specialization_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text='Código del curso (puede ser nulo para cursos paraguas)', max_length=20, null=True, unique=True),
        ),
    ]
