# Generated by Django 6.0.2 on 2026-03-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
