# Generated by Django 6.0.2 on 2026-03-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_careergoal_options_alter_interest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Preferencia', 'verbose_name_plural': 'Preferencias'},
        ),
        migrations.RemoveField(
            model_name='preference',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.AlterField(
            model_name='careergoal',
            name='icon',
            field=models.CharField(default='fa-bullseye', max_length=50),
        ),
        migrations.AlterField(
            model_name='interest',
            name='icon',
            field=models.CharField(default='fa-star', max_length=50),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(default='fa-code', max_length=50),
        ),
    ]
