# Generated by Django 6.0.2 on 2026-04-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_preference_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_semester',
            field=models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6'), (7, 'Semestre 7'), (8, 'Semestre 8'), (9, 'Semestre 9'), (10, 'Semestre 10')], default=1, help_text='Semestre actual del estudiante'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institutional_email',
            field=models.EmailField(blank=True, help_text='Correo institucional EAFIT', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil del estudiante', null=True, upload_to='profile_photos/'),
        ),
    ]
