# Generated by Django 6.0.2 on 2026-03-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_preference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Preference', 'verbose_name_plural': 'Preferences'},
        ),
    ]
