# Generated by Django 6.0.2 on 2026-05-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_current_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='english_level',
            field=models.CharField(choices=[('NONE', 'Sin nivel'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='NONE', help_text='Nivel de inglés certificado o completado', max_length=4),
        ),
    ]
