# Generated by Django 6.0.2 on 2026-05-19 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_english_level'),
        ('roadmap', '0006_specialization_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='ai_emphasis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap.emphasisline'),
        ),
        migrations.AddField(
            model_name='preference',
            name='ai_reasons',
            field=models.TextField(blank=True, help_text='Razones de la IA en formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='ai_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap.specialization'),
        ),
        migrations.AddField(
            model_name='preference',
            name='ai_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap.track'),
        ),
    ]
